### ISSUE TITLE
Enabling prefix option breaks source location in devtools

### ISSUE THREAD

**Issue by vidhill** [shellscape/loglevelnext#14]
* Node Version: v14.15.4
* NPM Version: 7.12.1
* loglevelnext Version: 4.0.1

This is a react app bundled with webpack version 4.46.0
Devtools are Google Chrome (Version 90.0.4430.93 (Official Build) (x86_64))

I can't quire understand why enabling the prefix factory changes this behaviour.
I realise this could easily be an issue with sourcemaps or Google Chrome

### JavaScript
**Scenario A:** No prefix enabled
```js
import loglevelnext from "loglevelnext";

const makeLogger = (name) => {
  const logger = loglevelnext.create({
    name,
    level: 1,
  });
  return logger;
};

export default makeLogger;
```

**Scenario B:** Prefix enabled
```js
import loglevelnext from "loglevelnext";

const makeLogger = (name) => {
  const logger = loglevelnext.create({
    name,
    level: 1,
    prefix: {
      template: "{{level}} ({{name}}) ",
    },
  });

  return logger;
};

export default makeLogger;

```

### Expected Behavior
With _scenario A_ config devtools logs point to the file where the logger logs the `index.jsx`
<img width="659" alt="Screenshot 2021-05-14 at 19 41 42" src="https://user-images.githubusercontent.com/3375475/118315265-34bd4480-b4ed-11eb-9c60-6dfd649e00ca.png">
This is desirable as you can click on the filename to jump to that line in the source

### Actual Behavior
Scenario A and B configuration should result in the same behaviour

With the _Scenario B_ configuration
devtools logs now point to the file the source of `PrefixFactory.js`

<img width="659" alt="Screenshot 2021-05-14 at 19 46 38" src="https://user-images.githubusercontent.com/3375475/118315937-1146c980-b4ee-11eb-80ca-2bee7ba4f7a0.png">

### How can we reproduce the behavior?
See above

**Comment by shellscape** [comment]
Hey thanks for reporting and using this little lib. Sounds like webpack is funging the sourcemaps. This isn't something that I get when running the lib as plain js inside of a browser. It's interesting, but you've got a super edgy edge case that doesn't look like it's impacting funcitonality.

**Comment by vidhill** [comment]
Yea, I was wondering if it could possibly be Webpack, 

It would have an impact on dev functionality/developer convenience.

**Comment by vidhill** [comment]
I will close this issue, as it does appear to be webpack specific.

**Comment by evoactivity** [comment]
I'm using vite and I'm seeing this issue. It makes using trace a little annoying since the stack includes the `make` call in `PrefixFactory.js`.

**Comment by shellscape** [comment]
@evoactivity as previous stated, this doesn't happen when the package isn't bundled. please present this to the vite team to recommend a fix.

**Comment by evoactivity** [comment]
@shellscape How else am I supposed to use it in a browser if not by bundling? The second sentence of the readme says to use your favourite bundler to use it in a browser. So I bundled it like every other dependancy.

None of these work.
```html
<script src="https://www.unpkg.com/loglevelnext@5.0.6/dist/index.js"></script>
```

```html
<script type="module" src="https://www.unpkg.com/loglevelnext@5.0.6/dist/index.js"></script>
```

```html
<script type="module">
import log from 'https://www.unpkg.com/loglevelnext@5.0.6/dist/index.js'
</script>
```

This is using it unbundled in node v18.11.0 seeing the same issue.

```js
// index.js
const logger = require('loglevelnext');
const log = logger.create({
  name: 'Test',
  level: 0,
  prefix: { template: '{{level}} [{{name}}] ' },
});

log.trace('hello');
```

```json
// package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "loglevelnext": "^5.0.6"
  }
}
```

output
```
$ > node index.js
Trace: [trace] [Test] hello
    at LogLevel.trace (/Users/{redacted}/node_modules/.pnpm/loglevelnext@5.0.6/node_modules/loglevelnext/dist/PrefixFactory.js:36:13)
    at Object.<anonymous> (/Users/{redacted}/packages/vanilla/index.cjs:8:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

I do not think this is a bundling issue.
