### ISSUE TITLE
Some links in the README.md are broken

### ISSUE THREAD

**Issue by vidhill** [shellscape/loglevelnext#16]
* Node Version: n/a
* NPM Version: n/a
* loglevelnext Version: master branch

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### Errors 

Clicking on `MethodFactory.js` links on the Github README.md links [here](https://github.com/shellscape/loglevelnext/blob/master/lib/MethodFactory.js)
Clicking on `PrefixFactory.js` links on the Github README.md links [here](https://github.com/shellscape/loglevelnext/blob/master/factory/PrefixFactory.js)

### Expected Behavior
Links should link to the expected location
### How can we reproduce the behavior?
Clicking on `MethodFactory.js` and `PrefixFactory.js` links on the Github README.md

**Comment by vidhill** [comment]
-I have a PR opened fixing these links

**Comment by shellscape** [comment]
Closed by #15
