### ISSUE TITLE
Should dist file still using `Object.assign`

### ISSUE THREAD

**Issue by vagusX** [shellscape/loglevelnext#4]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template.
**Please remove this header to acknowledge this message.**

* Operating System:
MacOS 10.13
* Node Version:
8.9
* Browser and Version (if applicable):
webview Chrome/40 on mobile phone
* NPM Version:
5.8
* loglevelnext Version:
1.0.3

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // code for your issue
```

### Expected Behavior
Using webpack-hot-client, it requires loglevelnext, but loglevel/dist/*.js contains a `Object.assign`

### Actual Behavior
Cannot work in the phone when debugging

**Comment by shellscape** [comment]
Thanks, fixed in 12ba8aa24ae691a8a16d6395d23eea953764c7ff
