### ISSUE TITLE
Internet Explorer 11 compatibility?

### ISSUE THREAD

**Issue by seanparmelee** [shellscape/loglevelnext#5]
Should loglevelnext work with IE11 out of the box? The [browser support](https://github.com/shellscape/loglevelnext#browser-support) section mentions IE 10 as the minimum IE version supported, but I'm running into a JS error when hitting my webpack-serve instance on IE 11 due to the use of `Symbol` in this library. If the intention is to support IE11, would you have any objection to replacing the `Symbol`s?

* Operating System: macOS 10.13.4
* Node Version: 8.11.0
* Browser and Version (if applicable): Internet Explorer 11 (running in a Windows 7 VM)
* NPM Version: 5.6.0
* loglevelnext Version: 1.0.4

- [x] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code
This affects anyone using webpack-hot-client along with Internet Explorer 11 as it chokes on [this line](https://github.com/shellscape/loglevelnext/blob/2a7ab4303beca56fb58ad2baa6a1894704c65275/lib/MethodFactory.js#L4) due to `Symbol` not being supported in Internet Explorer.

### Expected Behavior
Internet Explorer does not throw a "Symbol is undefined" error.

### Actual Behavior
Internet Explorer throws an error
```
'Symbol' is undefined
```

### For Bugs; How can we reproduce the behavior?
Spin up `webpack-serve` (or anything using webpack-hot-client) and access it with Internet Explorer 11. For those of us who aren't on a machine that has Internet Explorer, VMs are available [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

**Comment by shellscape** [comment]
Thanks for the issue 🍺  We actually don't need to _remove_ it, rather the `babel` config needs to be updated accordingly https://github.com/shellscape/loglevelnext/blob/master/.babelrc

**Comment by MatTheCat** [comment]
I can't test anything on BrowserStack due to this. What needs to be done exactly?

**Comment by shellscape** [comment]
@MatTheCat the babel config needs to be updated so that babel transforms without using `Symbol`

**Comment by MatTheCat** [comment]
Nope seems nothing changed :disappointed:

**Comment by shellscape** [comment]
@MatTheCat not sure what you're testing, but the bundle definitely has changed. If anything you can tell that by the filesize.

If that change didn't fix the issue then I'm afraid someone on Windows will have to debug this.

**Comment by seanparmelee** [comment]
`dist/loglevelnext.js` still references `Symbol`. I don't think you can configure babel to _not_ use Symbol, but you could either manually add a polyfill like you did for `Object.assign` or you can use the [useBuiltIns](https://github.com/babel/babel/tree/master/packages/babel-preset-env#usebuiltins) option and have babel-preset-env add it for you (along with anything else it thinks you need).

**Comment by shellscape** [comment]
One of you all (or someone else that uses Windows) is going to have to submit a PR to fix this for IE. Totally open to a PR that'll take care of this one. I just don't have time to mess with Windows at the moment.

**Comment by seanparmelee** [comment]
No problem, do you have a preference on how Symbol is polyfilled?

**Comment by shellscape** [comment]
@seanparmelee no preference at all. From my experience with `useBuiltins` I've seen bundle sizes increase dramatically when that option is enabled, so that's something to keep an eye on.
