### ISSUE TITLE
Please rebuild+publish with the latest object-keys dependency to remove Application Cache warning in Chrome

### ISSUE THREAD

**Issue by drsnyder** [shellscape/loglevelnext#7]
* Operating System: OS X
* Node Version: 10.7.0
* Browser and Version (if applicable): Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* NPM Version: 6.1.0
* loglevelnext Version: 1.0.5

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

`loglevelnext` is being included in our development builds via `webpack-serve`:
```
yarn why v1.7.0
[1/4] 🤔  Why do we have the module "loglevelnext"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "loglevelnext@1.0.5"
info Reasons this module exists
   - "webpack-serve#webpack-log" depends on it
   - Hoisted from "webpack-serve#webpack-log#loglevelnext"
   - Hoisted from "webpack-serve#webpack-hot-client#loglevelnext"
info Disk size without dependencies: "48MB"
info Disk size with unique dependencies: "220MB"
info Disk size with transitive dependencies: "4.47GB"
info Number of shared dependencies: 4
✨  Done in 1.01s.
```

When loading a page served in our environment using chrome, we get the following warning:
```
[Deprecation] Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.
```

The trace is as follows:
![screen shot 2018-08-27 at 10 19 08 am](https://user-images.githubusercontent.com/21621/44668322-ae7e0e80-a9e2-11e8-9373-23b221fa1514.png)

The warning is being generated by `object-keys` that's bundled with the current release. It has been addressed in the [latest version (1.0.12)](https://github.com/ljharb/object-keys/blob/master/CHANGELOG.md#1012--2018-06-18). Please rebuild and publish `loglevelnext`.

### Expected Behavior

This package should not generate any console warnings in Chrome.

### Actual Behavior

Console warnings are generated.

**Comment by shellscape** [comment]
vNext is going a different direction. Rather than pre-bundling for use in the browser, `loglevelnext` will have to be imported/required as part of a bundle, and polyfills added as needed for users' target environments.

Also of note; looks like the webpack folks have decided to kill webpack-serve, so it's doubtful webpack will continue to use this module in the future.

Sorry this one lingered so long. Closing citing the reasons listed.
